CREATE TABLE IF NOT EXISTS posts (
    post_source TEXT NOT NULL,
    post_html TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    id SERIAL UNIQUE NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS users (
    name VARCHAR(100) UNIQUE NOT NULL PRIMARY KEY ,
    pass_hash CHAR(64) NOT NULL,
    pass_salt CHAR(32) NOT NULL
);
